# Generated by Django 5.2.12 on 2026-03-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(db_index=True, max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=32)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True)),
            ],
        ),
    ]
