# Generated by Django 5.2.12 on 2026-03-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("COMPLETED_WITH_ERRORS", "Completed with errors"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=24,
            ),
        ),
    ]
